- project:
    queue: telemetry
    templates:
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - check-requirements
    check:
      jobs:
        - aodh-tox-py311-with-sqlalchemy-2x
        - aodh-tempest-plugin-mysql
        - aodh-tempest-plugin-postgresql
        - telemetry-dsvm-integration:
            irrelevant-files: &aodh-irrelevant-files
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
              - ^doc/.*$
              - ^.*\.rst$
              - ^releasenotes/.*$
              - ^aodh/tests/.*$
              - ^aodh/locale/.*$
              - ^tools/.*$
              - ^tox.ini$
            vars:
              # TODO: Update the plugins so they work with global venv
              devstack_localrc:
                GLOBAL_VENV: False
        - telemetry-dsvm-integration-ipv6-only:
            irrelevant-files: *aodh-irrelevant-files
            vars:
              # TODO: Update the plugins so they work with global venv
              devstack_localrc:
                GLOBAL_VENV: False
        - telemetry-dsvm-integration-centos-9s:
            irrelevant-files: *aodh-irrelevant-files
        - telemetry-dsvm-integration-centos-9s-fips:
            irrelevant-files: *aodh-irrelevant-files
    gate:
      jobs:
        - aodh-tempest-plugin-mysql
        - aodh-tempest-plugin-postgresql
        - telemetry-dsvm-integration:
            irrelevant-files: *aodh-irrelevant-files
            vars:
              # TODO: Update the plugins so they work with global venv
              devstack_localrc:
                GLOBAL_VENV: False
        - telemetry-dsvm-integration-ipv6-only:
            irrelevant-files: *aodh-irrelevant-files
            vars:
              # TODO: Update the plugins so they work with global venv
              devstack_localrc:
                GLOBAL_VENV: False
        - telemetry-dsvm-integration-centos-9s:
            irrelevant-files: *aodh-irrelevant-files
        - telemetry-dsvm-integration-centos-9s-fips:
            irrelevant-files: *aodh-irrelevant-files

- job:
    name: aodh-tox-py311-with-sqlalchemy-2x
    parent: openstack-tox-py311
    description: |
      Run unit tests with main branch of SQLAlchemy, alembic and oslo.db.
      Takes advantage of the base tox job's install-siblings feature.
    # The job only tests the latest and shouldn't be run on the stable branches
    branches: ^master$
    required-projects:
      - name: github.com/sqlalchemy/sqlalchemy
        override-checkout: main
      - name: github.com/sqlalchemy/alembic
        override-checkout: main
      - name: openstack/oslo.db

- job:
    name: aodh-tempest-plugin-postgresql
    parent: telemetry-tempest-base
    irrelevant-files: *aodh-irrelevant-files
    vars:
      devstack_services:
        postgresql: true
        mysql: false
      devstack_localrc:
        DATABASE_TYPE: postgresql
        AODH_BACKEND: postgresql
        USE_PYTHON3: True
        # TODO: Update the plugins so they work with global venv
        GLOBAL_VENV: False
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            telemetry_services:
              alarm_backend: postgresql
      tempest_test_regex: telemetry_tempest_plugin.aodh

- job:
    name: aodh-tempest-plugin-mysql
    parent: telemetry-tempest-base
    irrelevant-files: *aodh-irrelevant-files
    vars:
      devstack_localrc:
        AODH_BACKEND: "mysql"
        USE_PYTHON3: True
        # TODO: Update the plugins so they work with global venv
        GLOBAL_VENV: False
      tempest_test_regex: telemetry_tempest_plugin.aodh
