- project:
    templates:
      - openstack-python-jobs
      - openstack-python3-train-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - aodh-tempest-plugin-mysql
        - aodh-tempest-plugin-postgresql
        - telemetry-dsvm-integration
        - telemetry-dsvm-integration-ipv6-only
    gate:
      jobs:
        - aodh-tempest-plugin-mysql
        - aodh-tempest-plugin-postgresql
        - telemetry-dsvm-integration
        - telemetry-dsvm-integration-ipv6-only

- job:
    name: aodh-tempest-plugin-postgresql
    parent: telemetry-tempest-base
    irrelevant-files: &aodh-irrelevant-files
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
      - ^aodh/tests/.*$
    vars:
      devstack_services:
        postgresql: true
        mysql: false
      devstack_localrc:
        DATABASE_TYPE: "postgresql"
        AODH_BACKEND: "postgresql"
      tempest_test_regex: telemetry_tempest_plugin.aodh

- job:
    name: aodh-tempest-plugin-mysql
    parent: telemetry-tempest-base
    irrelevant-files: *aodh-irrelevant-files
    vars:
      devstack_localrc:
        AODH_BACKEND: "mysql"
      tempest_test_regex: telemetry_tempest_plugin.aodh
