- project:
    queue: telemetry
    templates:
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - check-requirements
    check:
      jobs:
        - aodh-tempest-plugin-mysql
        - aodh-tempest-plugin-postgresql
        - telemetry-dsvm-integration:
            irrelevant-files: &aodh-irrelevant-files
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
              - ^doc/.*$
              - ^.*\.rst$
              - ^releasenotes/.*$
              - ^aodh/tests/.*$
              - ^aodh/locale/.*$
              - ^tools/.*$
              - ^tox.ini$
        - telemetry-dsvm-integration-ipv6-only:
            irrelevant-files: *aodh-irrelevant-files
        - telemetry-dsvm-integration-centos-9s:
            irrelevant-files: *aodh-irrelevant-files
        - telemetry-dsvm-integration-centos-9s-fips:
            irrelevant-files: *aodh-irrelevant-files
    gate:
      jobs:
        - aodh-tempest-plugin-mysql
        - aodh-tempest-plugin-postgresql
        - telemetry-dsvm-integration:
            irrelevant-files: *aodh-irrelevant-files
        - telemetry-dsvm-integration-ipv6-only:
            irrelevant-files: *aodh-irrelevant-files
        - telemetry-dsvm-integration-centos-9s:
            irrelevant-files: *aodh-irrelevant-files
        - telemetry-dsvm-integration-centos-9s-fips:
            irrelevant-files: *aodh-irrelevant-files

- job:
    name: aodh-tempest-plugin-postgresql
    parent: telemetry-tempest-base
    irrelevant-files: *aodh-irrelevant-files
    vars:
      devstack_services:
        postgresql: true
        mysql: false
      devstack_localrc:
        DATABASE_TYPE: "postgresql"
        AODH_BACKEND: "postgresql"
        USE_PYTHON3: True
      tempest_test_regex: telemetry_tempest_plugin.aodh

- job:
    name: aodh-tempest-plugin-mysql
    parent: telemetry-tempest-base
    irrelevant-files: *aodh-irrelevant-files
    vars:
      devstack_localrc:
        AODH_BACKEND: "mysql"
        USE_PYTHON3: True
      tempest_test_regex: telemetry_tempest_plugin.aodh
